# Generated by Django 5.1.7 on 2025-03-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('wheel_size', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('grille_type', models.CharField(max_length=50)),
            ],
        ),
    ]
