# Generated by Django 5.1.7 on 2025-03-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carattributes',
            name='video_name',
        ),
        migrations.AlterField(
            model_name='carattributes',
            name='wheel_size',
            field=models.IntegerField(),
        ),
    ]
